# It may be tempting to add parens around each individual clause in this expression, but Travis then builds pushes anyway
if: branch = master OR branch =~ ^release/ OR tag IS present
language: go
go: 1.11
git:
    depth: false
sudo: true # give us 7.5GB and >2 bursted cores.
before_install:
    - git clone https://github.com/pulumi/scripts ${GOPATH}/src/github.com/pulumi/scripts
    - source ${GOPATH}/src/github.com/pulumi/scripts/ci/prepare-environment.sh
    - source ${PULUMI_SCRIPTS}/ci/keep-failed-tests.sh
install:
    - source ${PULUMI_SCRIPTS}/ci/install-common-toolchain.sh
before_script:
    - ${PULUMI_SCRIPTS}/ci/ensure-dependencies
after_failure:
    - ${PULUMI_SCRIPTS}/ci/upload-failed-tests
notifications:
    webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
jobs:
    include:
        - stage: build
          script: make travis_${TRAVIS_EVENT_TYPE}
        - stage: test-downstream
          name: Test Code Generation (AWS)
          if: type = pull_request
          script: ./scripts/test-downstream-impact pulumi-aws
        - stage: test-downstream
          name: Test Code Generation (Azure)
          if: type = pull_request
          script: ./scripts/test-downstream-impact pulumi-azure
        - stage: test-downstream
          name: Test Code Generation (GCP)
          if: type = pull_request
          script: ./scripts/test-downstream-impact pulumi-gcp
