env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

name: Automate Downstream Rollout
on:
  repository_dispatch:
    types:
      - automate-rollout
  workflow_dispatch:

jobs:
  downstream-provider:
    name: Upgrade ${{matrix.provider_name}} to latest pulumi-terraform-bridge
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@releases/v1
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@release/v1-alpha
        with:
          repo: pulumi/pulumictl
      - name: Check out source code
        uses: actions/checkout@master
      - name: Generate Downstream Code
        uses: pulumi/action-test-provider-downstream@c914c07257348cd989a0ca32acd68596beebf7dc
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          downstream-name: ${{ matrix.provider_name }}
          downstream-url: https://github.com/pulumi/${{ matrix.provider_name }}
          pulumi-bot-token: ${{ secrets.PULUMI_BOT_TOKEN }}
          github-actions-token: ${{ secrets.GITHUB_TOKEN }}
          use-provider-dir: true
          open-pull-request: true
    strategy:
      matrix:
        provider_name:
          - pulumi-keycloak
